import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import packageJson from "../../package.json";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark bg-[var(--color-blender-bg)] text-[var(--color-blender-text)]`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <div className="fixed bottom-2 right-2 text-xs text-gray-500/50 pointer-events-none z-50 select-none">
          v{packageJson.version}
        </div>
      </body>
    </html>
  );
}
